name: Obregon

on:
  push:
    branches: ["gh-obregon"]

jobs:
  # OBREGON
  gh_estadio_yaqui:
    runs-on:
      - self-hosted
      - gh_estadio_yaqui
    steps:
      - uses: actions/checkout@v3
      - name: Install Dependencies
        run: composer install -q --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist
      - name: Limpiar cache
        run: php artisan cache:clear
      - name: Limpiar cache config
        run: php artisan config:cache
      - name: Limpiar cache route
        run: php artisan route:cache
      - name: Limpiar cache view
        run: php artisan view:cache

  gh_menudeo_mercadito:
    runs-on:
      - self-hosted
      - gh_menudeo_mercadito
    steps:
      - uses: actions/checkout@v3
      - name: Install Dependencies
        run: composer install -q --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist
      - name: Limpiar cache
        run: php artisan cache:clear
      - name: Limpiar cache config
        run: php artisan config:cache
      - name: Limpiar cache route
        run: php artisan route:cache
      - name: Limpiar cache view
        run: php artisan view:cache

  gh_menudeo_200:
    runs-on:
      - self-hosted
      - gh_menudeo_200
    steps:
      - uses: actions/checkout@v3
      - name: Install Dependencies
        run: composer install -q --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist
      - name: Limpiar cache
        run: php artisan cache:clear
      - name: Limpiar cache config
        run: php artisan config:cache
      - name: Limpiar cache route
        run: php artisan route:cache
      - name: Limpiar cache view
        run: php artisan view:cache

  gh_menudeo_nainari:
    runs-on:
      - self-hosted
      - gh_menudeo_nainari
    steps:
      - uses: actions/checkout@v3
      - name: Install Dependencies
        run: composer install -q --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist
      - name: Limpiar cache
        run: php artisan cache:clear
      - name: Limpiar cache config
        run: php artisan config:cache
      - name: Limpiar cache route
        run: php artisan route:cache
      - name: Limpiar cache view
        run: php artisan view:cache

  gh_menudeo_misiones:
    runs-on:
      - self-hosted
      - gh_menudeo_misiones
    steps:
      - uses: actions/checkout@v3
      - name: Install Dependencies
        run: composer install -q --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist
      - name: Limpiar cache
        run: php artisan cache:clear
      - name: Limpiar cache config
        run: php artisan config:cache
      - name: Limpiar cache route
        run: php artisan route:cache
      - name: Limpiar cache view
        run: php artisan view:cache

  gh-guaymas:
    runs-on:
      - self-hosted
      - gh-guaymas
    steps:
      - uses: actions/checkout@v3
      - name: Install Dependencies
        run: composer install -q --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist
      - name: Limpiar cache
        run: php artisan cache:clear
      - name: Limpiar cache config
        run: php artisan config:cache
      - name: Limpiar cache route
        run: php artisan route:cache
      - name: Limpiar cache view
        run: php artisan view:cache
