name: Posweb2

on:
  push:
    branches: ["gh-production"]

jobs:
  gh-ke-planta:
    runs-on:
      - self-hosted
      - gh-ke-planta
    steps:
      - uses: actions/checkout@v3
      - name: Install Dependencies
        run: composer install -q --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist
      - name: Limpiar cache
        run: php artisan cache:clear
      - name: Limpiar cache config
        run: php artisan config:cache
      - name: Limpiar cache route
        run: php artisan route:cache
      - name: Limpiar cache view
        run: php artisan view:cache

  gh-desarrollo:
    runs-on:
      - self-hosted
      - gh-desarrollo
    steps:
      - uses: actions/checkout@v3
      - name: Install Dependencies
        run: composer install -q --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist
      - name: Limpiar cache
        run: php artisan cache:clear
      - name: Limpiar cache config
        run: php artisan config:cache
      - name: Limpiar cache route
        run: php artisan route:cache
      - name: Limpiar cache view
        run: php artisan view:cache

  gh-d-ke-talamante:
    runs-on:
      - self-hosted
      - gh-d-ke-talamante
    steps:
      - uses: actions/checkout@v3
      - name: Install Dependencies
        run: composer install -q --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist
      - name: Limpiar cache
        run: php artisan cache:clear
      - name: Limpiar cache config
        run: php artisan config:cache
      - name: Limpiar cache route
        run: php artisan route:cache
      - name: Limpiar cache view
        run: php artisan view:cache

  gh-ke-comedor-2:
    runs-on:
      - self-hosted
      - gh-ke-comedor-2
    steps:
      - uses: actions/checkout@v3
      - name: Install Dependencies
        run: composer install -q --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist
      - name: Limpiar cache
        run: php artisan cache:clear
      - name: Limpiar cache config
        run: php artisan config:cache
      - name: Limpiar cache route
        run: php artisan route:cache
      - name: Limpiar cache view
        run: php artisan view:cache

  gh-ke-comedor:
    runs-on:
      - self-hosted
      - gh-ke-comedor
    steps:
      - uses: actions/checkout@v3
      - name: Install Dependencies
        run: composer install -q --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist
      - name: Limpiar cache
        run: php artisan cache:clear
      - name: Limpiar cache config
        run: php artisan config:cache
      - name: Limpiar cache route
        run: php artisan route:cache
      - name: Limpiar cache view
        run: php artisan view:cache

  gh_menudeo_estadio:
    runs-on:
      - self-hosted
      - gh-menudeo-estadio
    steps:
      - uses: actions/checkout@v3
      - name: Install Dependencies
        run: composer install -q --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist
      - name: Limpiar cache
        run: php artisan cache:clear
      - name: Limpiar cache config
        run: php artisan config:cache
      - name: Limpiar cache route
        run: php artisan route:cache
      - name: Limpiar cache view
        run: php artisan view:cache

  gh_menudeo_estadio_2:
    runs-on:
      - self-hosted
      - gh-menudeo-estadio-2
    steps:
      - uses: actions/checkout@v3
      - name: Install Dependencies
        run: composer install -q --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist
      - name: Limpiar cache
        run: php artisan cache:clear
      - name: Limpiar cache config
        run: php artisan config:cache
      - name: Limpiar cache route
        run: php artisan route:cache
      - name: Limpiar cache view
        run: php artisan view:cache

  gh_aux:
    runs-on:
      - self-hosted
      - gh-aux
    steps:
      - uses: actions/checkout@v3
      - name: Install Dependencies
        run: composer install -q --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist
      - name: Limpiar cache
        run: php artisan cache:clear
      - name: Limpiar cache config
        run: php artisan config:cache
      - name: Limpiar cache route
        run: php artisan route:cache
      - name: Limpiar cache view
        run: php artisan view:cache

  gh_menudeo_alamos:
    runs-on:
      - self-hosted
      - gh_menudeo_alamos
    steps:
      - uses: actions/checkout@v3
      - name: Install Dependencies
        run: composer install -q --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist
      - name: Limpiar cache
        run: php artisan cache:clear
      - name: Limpiar cache config
        run: php artisan config:cache
      - name: Limpiar cache route
        run: php artisan route:cache
      - name: Limpiar cache view
        run: php artisan view:cache

  gh-menudeo-pork:
    runs-on:
      - self-hosted
      - gh-menudeo-pork
    steps:
      - uses: actions/checkout@v3
      - name: Install Dependencies
        run: composer install -q --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist
      - name: Limpiar cache
        run: php artisan cache:clear
      - name: Limpiar cache config
        run: php artisan config:cache
      - name: Limpiar cache route
        run: php artisan route:cache
      - name: Limpiar cache view
        run: php artisan view:cache

  gh-menudeo-hidalgo:
    runs-on:
      - self-hosted
      - gh-menudeo-hidalgo
    steps:
      - uses: actions/checkout@v3
      - name: Install Dependencies
        run: composer install -q --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist
      - name: Limpiar cache
        run: php artisan cache:clear
      - name: Limpiar cache config
        run: php artisan config:cache
      - name: Limpiar cache route
        run: php artisan route:cache
      - name: Limpiar cache view
        run: php artisan view:cache

  gh-menudeo-sonora:
    runs-on:
      - self-hosted
      - gh-menudeo-sonora
    steps:
      - uses: actions/checkout@v3
      - name: Install Dependencies
        run: composer install -q --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist
      - name: Limpiar cache
        run: php artisan cache:clear
      - name: Limpiar cache config
        run: php artisan config:cache
      - name: Limpiar cache route
        run: php artisan route:cache
      - name: Limpiar cache view
        run: php artisan view:cache

