name: Posweb2

on:
  push:
    branches: ["gh-production"]

jobs:
  common-steps:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v3
      - name: Install Dependencies
        run: composer install -q --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist
      - name: Limpiar cache
        run: php artisan cache:clear
      - name: Limpiar cache config
        run: php artisan config:cache
      - name: Limpiar cache route
        run: php artisan route:cache
      - name: Limpiar cache view
        run: php artisan view:cache

  gh-ke-planta:
    needs: common-steps
    runs-on: gh-ke-planta
    steps: *common-steps

  gh-desarrollo:
    needs: common-steps
    runs-on: gh-desarrollo
    steps: *common-steps

  gh-talamante:
    needs: common-steps
    runs-on: gh-talamante
    steps: *common-steps

  gh-ke-comedor-2:
    needs: common-steps
    runs-on: gh-ke-comedor-2
    steps: *common-steps

  gh-ke-comedor:
    needs: common-steps
    runs-on: gh-ke-comedor
    steps: *common-steps

  gh_menudeo_estadio:
    needs: common-steps
    runs-on: gh-menudeo-estadio
    steps: *common-steps

  gh_aux:
    needs: common-steps
    runs-on: gh-aux
    steps: *common-steps

  gh_menudeo_alamos:
    needs: common-steps
    runs-on: gh_menudeo_alamos
    steps: *common-steps

  gh-menudeo-pork:
    needs: common-steps
    runs-on: gh-menudeo-pork
    steps: *common-steps

  gh-menudeo-hidalgo:
    needs: common-steps
    runs-on: gh-menudeo-hidalgo
    steps: *common-steps

  gh-menudeo-sonora:
    needs: common-steps
    runs-on: gh-menudeo-sonora
    steps: *common-steps

  # OBREGON
  gh_estadio_yaqui:
    needs: common-steps
    runs-on: gh_estadio_yaqui
    steps: *common-steps

  gh_menudeo_mercadito:
    needs: common-steps
    runs-on: gh_menudeo_mercadito
    steps: *common-steps

  gh_menudeo_200:
    needs: common-steps
    runs-on: gh_menudeo_200
    steps: *common-steps

  gh_menudeo_nainari:
    needs: common-steps
    runs-on: gh_menudeo_nainari
    steps: *common-steps

  gh_menudeo_misiones:
    needs: common-steps
    runs-on: gh_menudeo_misiones
    steps: *common-steps
