name: Posweb2

on:
  push:
    branches: ["feat-upgrade"]

jobs:
  gh-test:
    runs-on:
      - self-hosted
      - gh-ke-planta
    steps:
      - uses: actions/checkout@v3
      - name: Install Dependencies
        run: composer install -q --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist
      - name: Limpiar cache
        run: php artisan cache:clear
      - name: Limpiar cache config
        run: php artisan config:cache
      - name: Limpiar cache route
        run: php artisan route:cache
      - name: Limpiar cache view
        run: php artisan view:cache
